# [START runtime]
runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT djangoapi.wsgi

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /static
  static_dir: static
- url: .*
  secure: always
  script: auto
beta_settings:
    cloud_sql_instances: esc10-303807:asia-southeast1:escdb

runtime_config:
  python_version: 3
# [END runtime]