# Generated by Django 3.1.5 on 2021-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
