# Generated by Django 3.1.5 on 2021-03-23 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='unresolved_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='case',
            name='non_compliance_type',
            field=models.CharField(choices=[('Professional & Staff Hygiene', 'Professional & Staff Hygiene'), ('Housekeeping & General Cleanliness', 'Housekeeping & General Cleanliness'), ('Workplace Safety & Health', 'Workplace Safety & Health'), ('Healthier Choice', 'Healthier Choice'), ('Food Hygiene', 'Food Hygiene')], max_length=100),
        ),
    ]
