# Generated by Django 3.1.5 on 2021-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcase',
            name='month',
            field=models.DateTimeField(),
        ),
    ]
