# Generated by Django 3.1.5 on 2021-02-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210204_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
