# Generated by Django 3.1.5 on 2021-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210408_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='unresolved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
