# Generated by Django 3.1.5 on 2021-03-11 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('news_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
