# Generated by Django 3.1.5 on 2021-03-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210323_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='is_Resolved',
            new_name='is_resolved',
        ),
    ]
