# Generated by Django 3.1.5 on 2021-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210408_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcase',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resolvedcase',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
    ]
