# Generated by Django 3.1.5 on 2021-03-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='foodhygiene_score',
        ),
    ]
