# Generated by Django 3.1.5 on 2021-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_report_foodhygiene_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='foodhygiene_score',
            field=models.IntegerField(default=0),
        ),
    ]
