# Generated by Django 3.1.5 on 2021-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210408_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedcase',
            old_name='report_id',
            new_name='tenant_id',
        ),
        migrations.RenameField(
            model_name='resolvedcase',
            old_name='report_id',
            new_name='tenant_id',
        ),
        migrations.AddField(
            model_name='case',
            name='tenant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
