# Generated by Django 3.1.5 on 2021-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210204_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='foodhygiene_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='healthierchoice_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='housekeeping_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='safety_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='staffhygiene_score',
            field=models.BooleanField(default=False),
        ),
    ]
