# Generated by Django 3.1.5 on 2021-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_foodhygiene_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='foodhygiene_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='healthierchoice_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='housekeeping_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='safety_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='staffhygiene_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
