# Generated by Django 3.1.5 on 2021-04-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210408_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolvedcase',
            name='tenant_id',
        ),
    ]
