# Generated by Django 3.1.5 on 2021-02-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210204_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='foodhygiene',
        ),
        migrations.RemoveField(
            model_name='report',
            name='healthierchoice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='housekeeping',
        ),
        migrations.RemoveField(
            model_name='report',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='report',
            name='staffhygiene',
        ),
    ]
