# Generated by Django 3.1.5 on 2021-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_resolvedcase_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedcase',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
    ]
