# Generated by Django 3.1.5 on 2021-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210321_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('unresolved_photo', models.TextField()),
                ('resolved_photo', models.CharField(max_length=100)),
                ('resolved_comments', models.TextField()),
                ('check', models.CharField(max_length=3)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
