# Generated by Django 3.1.5 on 2021-03-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='status',
            new_name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='case',
            name='check',
        ),
    ]
