# Generated by Django 3.1.5 on 2021-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210411_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rejected_comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='institution',
            field=models.CharField(max_length=30),
        ),
    ]
