# Generated by Django 3.1.5 on 2021-02-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210204_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolution_image',
        ),
    ]
