# Generated by Django 3.1.5 on 2021-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210204_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(default='Null', max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('institution', models.CharField(default='Null', max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
