# Generated by Django 3.1.5 on 2021-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210309_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='stall',
        ),
        migrations.AddField(
            model_name='report',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='auditor_id',
            field=models.IntegerField(default=0),
        ),
    ]
