# Generated by Django 3.1.6 on 2021-02-04 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('auditor_id', models.CharField(max_length=30)),
                ('stall', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('outlet_type', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('report_notes', models.CharField(max_length=500)),
                ('report_date', models.DateTimeField(default=datetime.datetime.now)),
                ('report_image', models.CharField(max_length=200)),
                ('resolution_notes', models.CharField(blank=True, max_length=500)),
                ('resolution_date', models.CharField(blank=True, max_length=100)),
                ('resolution_image', models.CharField(blank=True, max_length=200)),
                ('staffhygiene_score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('housekeeping_score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('safety_score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('healthierchoice_score', models.DecimalField(decimal_places=2, max_digits=20)),
                ('foodhygiene_score', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
