# Generated by Django 3.1.5 on 2021-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210204_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='case_id',
        ),
    ]
