# Generated by Django 3.1.5 on 2021-02-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_report_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='foodhygiene_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='healthierchoice_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='housekeeping_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='safety_score',
        ),
        migrations.RemoveField(
            model_name='report',
            name='staffhygiene_score',
        ),
    ]
