# Generated by Django 3.1.5 on 2021-02-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210204_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='foodhygiene_score',
            new_name='foodhygiene',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='healthierchoice_score',
            new_name='healthierchoice',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='housekeeping_score',
            new_name='housekeeping',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='safety_score',
            new_name='safety',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='staffhygiene_score',
            new_name='staffhygiene',
        ),
    ]
